### ISSUE TITLE
JDK 12 support

### ISSUE THREAD

**Issue by nikeee** [jenkinsci/docker-slave#70]
Is there a plan to publish a `latest-jdk12` or r a `jdk-12-alpine` version of this image?

**Comment by slide** [comment]
Why do you need a JDK12 version? This is not the JDK that will necessarily be used for builds, just for running the agent jar. You can still run BUILDs with a JDK12 even if the container is running the agent under JDK11 or JDK8.

**Comment by oleg-nenashev** [comment]
No plan at the moment. We can definitely deliver #71, but adding more platforms to this repo is not sustainable until we do refactoring of the packaging flow. I might have time for that in September after GSoC, but hard to commit on that.

We also do not have any kind of test automation for Jenkins with JDK12. Last time I tried it on my instance, it was failing on Debian due to some process management issues.
